### ISSUE TITLE
too many sections in jpg file error

### ISSUE THREAD

**Issue by fgerent** [akkana/pho#7]
Hi, I've been using pho to look at some pictures from an old phone (Motorola G5S) and kept getting the error above for many of the files. The error causes pho to stop and no output is produced (e.g. notes or rotation info for previous files) other than the error message.
I have found a workaround for the issue, which was to change the hardcoded MAX_SECTIONS (in exif/jpgfile.c) from 20 to 100 and recompile. I haven't noticed any adverse effects since making the change, and I haven't gotten the error since.
Perhaps this number should be increased or alternatively an argument could be passed at run time to override it (something like --max-sections=100).
Thanks.

**Comment by akkana** [comment]
Sorry for the long delay. I've bumped MAX_SECTIONS to 100 as you suggested.
